name: Build and Push to Cachix

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - nixtest1
          - nixtest2
    steps:
      # actions/checkout@v4
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      # cachix/install-nix-action@v30
      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      # cachix/cachix-action@v15
      - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc
        with:
          name: brauni
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build ${{ matrix.host }}
        run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
